#!/data/data/com.termux/files/usr/bin/bash

. $MOTD/colors
current='/mnt/d/Clouds/Dropbox/Personal/current'

IP=`cat $current/laptop_wsl_kali_IP.txt`

echo -e "$C  Public IP : $W$IP"

#printf "\n  Current IP:"

