#!/data/data/com.termux/files/usr/bin/bash

#12345678901234567890123456789012345678901234567890
#0        1         2         3         4         5

# config
max_usage=90
bar_width=42
. $MOTD/colors

# disk usage: ignore zfs, squashfs & tmpfs
# only the ones on board
mapfile -t dfs < <(df -H -t ext4 -t 9p | grep -v Docker | tail -n+2)
printf "\n  ${BOLD}Disk Usage:${NC}\n"
not_first=false
for line in "${dfs[@]}"; do
    lines=$(echo $line | awk '{ print $6 }')
    len=$(expr length $lines)
    if (( len < 8 )); then
        #echo $len' - >'$lines'<'
        # get disk usage
        usage=$(echo "$line" | awk '{print $5}' | sed 's/%//')
        used_width=$((($usage*$bar_width)/100))
        # color is green if usage < max_usage, else red
        if [ "${usage}" -ge "${max_usage}" ]; then
            color=$R
        else
            color=$G
        fi
        # print green/red bar until used_width
        bar="[${color}"
        for ((i=0; i<$used_width; i++)); do
            bar+="#"
        done
        # print dimmmed bar until end
        bar+="${W}${D}"
        for ((i=$used_width; i<$bar_width; i++)); do
            bar+="-"
        done
        bar+="${U}]"
        # print usage line & bar
	if [ $not_first == 'true' ]; then
		echo
	else
		not_first='true'
	fi
        echo "${line}" | awk '{ printf("%-21s%+4s used out of %+4s\n", $6, $3, $2); }' | sed -e 's/^/   /'
        echo -e "${bar}" | sed -e 's/^/  /'
    fi
done
